Draft: docs: Generate documentation with sphinx
adfinis/pyaptly pull request #121
Opened 2024-11-11 07:58 UTC by Melkor333

This PR will add documentation generation with sphinx.
It's using (a manually patched version of) [md-click](https://pypi.org/project/md-click/) (I sent upstream a mail hoping they might merge one of the fixes...) and `autodocs` to generate docs for the most relevant code.

TODOs:
- [ ] Make the `index.rst` a bit more pretty. Optimally it would show the content of the `README.md`. Maybe we should convert it to `rst` and then just merge it into the `index.rst` 🤔 
- [ ] We really need to write some docs on the `config.toml`
  - The examples in the `test` folder are very useful and might be reused for this.
  - As seen in #120 it's not always clear what Features even exist -> we need reference docs as well. I was thinking about defining a  [json-schema](https://python-jsonschema.readthedocs.io/en/stable/) and using [jsonschema-markdown](https://pypi.org/project/jsonschema-markdown/). This way we also get validation "for free", something that should happen at some point.

2024-11-11 07:59 UTC, Melkor333 commented
This should also close #113 when finished.

2024-11-13 09:27 UTC, Melkor333 commented
Got internal feedback that maybe gitbook or vuebook might be a "more modern" approach than going back to sphinx... Since everything is markdown the only missing piece would be the pydocs which could probably be converted to md with something like [pydoc-markdown](https://pypi.org/project/pydoc-markdown/)

2024-12-19 10:53 UTC, winged requested changes
Awesome work! I only have a little nitpick, otherwise LGTM!

2024-12-19 12:42 UTC, Melkor333 commented on pyaptly/main.py
> +    jsonschema=json.load(file)
Thanks! I knew this code's gonna require some changes 😄

2024-12-23 10:12 UTC, winged approved these changes

2024-12-23 10:17 UTC, merged